### ISSUE TITLE
java.lang.RuntimeException: couldn't find method <clinit>(*) in com.scort.es.jndi.url.URLContext

### ISSUE THREAD

**Issue by zosrothko** [adoptium/emt4j#40]
Hi

Got this third one below
```
java.lang.RuntimeException: couldn't find method <clinit>(*) in com.scort.es.jndi.url.URLContext
        at soot.SootClass.getMethodByName(SootClass.java:609)
        at org.eclipse.emt4j.common.staticanalysis.impl.BaseAnalyzer.globalTarget(BaseAnalyzer.java:97)
        at org.eclipse.emt4j.common.staticanalysis.impl.BaseAnalyzer.getDefValues(BaseAnalyzer.java:68)
        at org.eclipse.emt4j.common.staticanalysis.impl.CLDRDateFormatAnalyzer.isTarget(CLDRDateFormatAnalyzer.java:67)
        at org.eclipse.emt4j.common.staticanalysis.impl.CLDRDateFormatAnalyzer.doAnalyze(CLDRDateFormatAnalyzer.java:56)
        at org.eclipse.emt4j.common.staticanalysis.impl.BaseAnalyzer.analyze(BaseAnalyzer.java:45)
        at org.eclipse.emt4j.common.staticanalysis.impl.CLDRDateFormatAnalyzer.analyze(CLDRDateFormatAnalyzer.java:33)  Analyze classes done

        at org.eclipse.emt4j.common.staticanalysis.InvokerImpl.invoke(InvokerImpl.java:117)
        at org.eclipse.emt4j.common.staticanalysis.StaticAnalysisEntry.analyze(StaticAnalysisEntry.java:75)
        at org.eclipse.emt4j.common.rule.impl.WholeClassRule.check(WholeClassRule.java:68)
        at org.eclipse.emt4j.common.rule.ExecutableRule.execute(ExecutableRule.java:70)
        at org.eclipse.emt4j.analysis.AnalysisExecutor.lambda$null$1(AnalysisExecutor.java:99)
        at org.eclipse.emt4j.analysis.analyzer.ClassAnalyzer.processClass(ClassAnalyzer.java:65)
        at org.eclipse.emt4j.analysis.analyzer.ClassAnalyzer.analyze(ClassAnalyzer.java:42)
        at org.eclipse.emt4j.analysis.analyzer.DependencyAnalyzer.iterateDo(DependencyAnalyzer.java:54)
  Analyze classes done
        at org.eclipse.emt4j.analysis.source.DirectorySource.parse(DirectorySource.java:48)
        at org.eclipse.emt4j.analysis.AnalysisExecutor.lambda$execute$2(AnalysisExecutor.java:91)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)  Analyze ctgclient-4.0.jar done

        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)  Analyze slf4j-reload4j-1.7.35.jar done

        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by D-D-H** [comment]
Hi, this problem has been fixed by https://github.com/adoptium/emt4j/commit/dd607cabe05b31b9982661ef25e8d1b16e56e93d.
