### ISSUE TITLE
 java.lang.InterruptedException when put dependency in ReportRecorder

### ISSUE THREAD

**Issue by qiuchenjian** [adoptium/emt4j#54]
Hi
Has anyone seen this problem? 
```
org.apache.maven.plugins:maven-surefire-plugin:2.19:test failed: There was an error in the forked process
[ERROR] org.apache.maven.surefire.testset.TestSetFailedException: java.lang.RuntimeException: java.lang.InterruptedException
[ERROR] 	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.rethrowAnyTestMechanismFailures(JUnit4RunListener.java:209)
[ERROR] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:131)
[ERROR] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:101)
[ERROR] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:77)
[ERROR] 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:177)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: java.lang.RuntimeException: java.lang.InterruptedException
[ERROR] 	at org.eclipse.emt4j.agent.common.AgentFacade.record(AgentFacade.java:136)
[ERROR] 	at org.eclipse.emt4j.agent.common.rule.systemclassloader.GetSystemClassLoaderCallback.enter(GetSystemClassLoaderCallback.java:41)
[ERROR] 	at java.lang.Class.getClassLoader(Class.java:685)
[ERROR] 	at org.junit.runner.Description.getTestClass(Description.java:288)
[ERROR] 	at org.apache.maven.surefire.junitcore.NonConcurrentRunListener.describesNewTestSet(NonConcurrentRunListener.java:93)
[ERROR] 	at org.apache.maven.surefire.junitcore.NonConcurrentRunListener.finishLastTestSetIfNecessary(NonConcurrentRunListener.java:77)
[ERROR] 	at org.apache.maven.surefire.junitcore.NonConcurrentRunListener.testFailure(NonConcurrentRunListener.java:130)
[ERROR] 	at org.junit.runner.notification.SynchronizedRunListener.testFailure(SynchronizedRunListener.java:63)
[ERROR] 	at org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:142)
[ERROR] 	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
[ERROR] 	at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:138)
[ERROR] 	at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:132)
[ERROR] 	at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:23)
[ERROR] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:369)
[ERROR] 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
[ERROR] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:130)
[ERROR] 	... 6 more
[ERROR] Caused by: java.lang.InterruptedException
[ERROR] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1222)
[ERROR] 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
[ERROR] 	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
[ERROR] 	at org.eclipse.emt4j.agent.common.file.ReportRecorder.record(ReportRecorder.java:74)
[ERROR] 	at org.eclipse.emt4j.agent.common.AgentFacade.record(AgentFacade.java:133)
[ERROR] 	... 21 more
```

**Comment by qiuchenjian** [comment]
```
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1222)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
	at org.eclipse.emt4j.agent.common.file.ReportRecorder.record(ReportRecorder.java:74)
	at org.eclipse.emt4j.agent.common.AgentFacade.recordLoadClass(AgentFacade.java:150)
	at org.eclipse.emt4j.agent.common.InspectTransformer.transform(InspectTransformer.java:47)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:493)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:75)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:389)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:383)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.maven.surefire.booter.ForkedBooter.launchLastDitchDaemonShutdownThread(ForkedBooter.java:263)
	at org.apache.maven.surefire.booter.ForkedBooter.exit(ForkedBooter.java:224)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:142)
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1222)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
	at org.eclipse.emt4j.agent.common.file.ReportRecorder.record(ReportRecorder.java:74)
	at org.eclipse.emt4j.agent.common.AgentFacade.recordLoadClass(AgentFacade.java:150)
	at org.eclipse.emt4j.agent.common.InspectTransformer.transform(InspectTransformer.java:47)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.util.IdentityHashMap$KeySet.iterator(IdentityHashMap.java:979)
	at java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:101)
	at java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
	at java.lang.Shutdown.runHooks(Shutdown.java:130)
	at java.lang.Shutdown.exit(Shutdown.java:178)
	at java.lang.Runtime.exit(Runtime.java:103)
	at java.lang.System.exit(System.java:987)
	at org.apache.maven.surefire.booter.ForkedBooter.exit(ForkedBooter.java:225)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:142)
```
